### ISSUE TITLE
Old plugin reference

### ISSUE THREAD

**Issue by Sonic0** [mastertinner/dotfiles#2]
https://github.com/mastertinner/dotfiles/blob/fb373d3a12f28a720f77d4862418653fdff0f4fb/vim/.plugins.vimrc#L75

Hi Tobi,
I think that this is an old reference to ALE. I have installed this plugin by `Plug 'dense-analysis/ale'`.
Maybe, the owner has moved Ale to this new repo -> [dense-analysis/ale](https://github.com/dense-analysis/ale#3iiii-installation-with-vim-plug)

**Comment by cloudlena** [comment]
Thanks, @Sonic0! It's fixed. I appreciate the feedback!
