### ISSUE TITLE
redshift-wlr-gamma-control-git

### ISSUE THREAD

**Issue by Sonic0** [mastertinner/dotfiles#3]
Hi @mastertinner,
I found out an issue with the package _redshift-wlr-gamma-control-git_. It's no longer exists, although it's possible it changed its name.

**Comment by cloudlena** [comment]
Thanks, @Sonic0. Good catch. I noticed that too... I'm desperately waiting for https://github.com/jonls/redshift/pull/663 to get merged to be able to use redshift again with Sway.

**Comment by Sonic0** [comment]
Oh yes, I read something about it on Reddit. Thank you very much to share with us your dotfiles.

**Comment by cloudlena** [comment]
My pleasure. Thanks for using them and reporting issues! :)
